from pathlib import Path
import re, sys
if len(sys.argv)!=2: raise SystemExit('usage: manual-v50-0-2.py <project-root>')
root=Path(sys.argv[1]).resolve(); p=root/'src/ClassicUO.Client/YokoDocumentation/Manual/COMPLETE_RUNTIME_API_MANUAL.md'
s=p.read_text(encoding='utf-8-sig')

def card(name, signatures, rtype, rcontract, params, behavior, notes, examples):
    sig='\n'.join(f'- `{x}`' for x in signatures)
    return f'''## `UO.{name}`\n\n### Current v50.0.2 signatures / Return\n\n{sig}\n\n**Return type:** `{rtype}`\n\n**Return contract:** {rcontract}\n\n### Parameters\n\n{params}\n\n### Behavior\n\n{behavior}\n\n### Notes / limitations\n\n{notes}\n\n### Examples\n\n```basic\n{examples}\n```\n\n---'''

C={}
C['Hide']=card('Hide',['UO.Hide() -> Unit','UO.Hide(serial:ObjectRef) -> Unit'],'Unit','No value. Success is the actual persistent local hidden state of the selected/resolved loaded object.','`serial` is a loaded item/mobile serial or supported object reference. The player itself is rejected.','`Hide()` opens Target; `Hide(serial)` acts immediately. v50.0.2 sets a persistent `ClientHidden` flag. `AllowedToDraw` may be recalculated by scene code, but its effective getter remains false while `ClientHidden` is true, so the object does not reappear on the next renderer pass.','This is client-side visibility, not the Hiding skill. The object remains in ClassicUO World; no delete is sent to the server. Reload/resync/reconnect may create a new visible object instance.','UO.Hide()\nUO.Hide(0x40001234)')
C['ClientHide']=card('ClientHide',['UO.ClientHide(ObjID:Integer) -> Boolean'],'Boolean','TRUE only if a real loaded non-player entity was found and is actually persistent-client-hidden; otherwise FALSE.','`ObjID` is the loaded item/mobile serial.','Uses the same persistent `ClientHidden` state as `Hide(serial)`. The old fixed-TRUE route is removed.','Local only; server and other clients are not notified. Missing/destroyed object or self returns FALSE.','IF UO.ClientHide(0x40001234) THEN\n    UO.Print("hidden")\nEND IF')
C['InfoGump']=card('InfoGump',['UO.InfoGump() -> Unit','UO.InfoGump(gump:Variant) -> Unit'],'Unit','No value. Final effect is an inspector document built from the currently loaded real server Gump.','Without argument: newest active server Gump. With argument: current Yoko index, stable InjID, local Serial or server GumpID.','Uses `IsFromServer`, not `GumpID != 0`, so a real server Gump with GumpID 0 is valid. The inspector shows index, Serial, GumpID, stable InjID, position/size/page, actual controls and ButtonID values, and exact raw server layout commands retained from the incoming packet. The inspected Gump becomes the selection for GetGump/SetGump.','Yoko index 0 is the newest active Gump because ClassicUO inserts new Gumps at the front. Selection does not redefine LastGump or one-argument SendGumpSelect.','UO.InfoGump()\nUO.InfoGump(0)')
C['InfoGumps']=card('InfoGumps',['UO.InfoGumps() -> Unit','UO.InfoGumps(gump:Variant) -> Unit'],'Unit','No value. Opens a current snapshot list or detailed inspector.','No argument lists all active server Gumps; argument opens detail for the requested Gump.','Lists only non-disposed `IsFromServer` Gumps from the current World, including GumpID 0. Each row contains Yoko index, stable InjID, GumpID, Serial, position, size, page and control count.','Yoko list order is newest first.','UO.InfoGumps()')
C['LastGump']=card('LastGump',['UO.LastGump(identifier:String) -> Any','UO.LastGump(identifier:String, key:Integer) -> Any'],'Any','Field-dependent Integer/String value from the newest active server Gump.','`identifier`: serial, gumpid, injid, replyed, inclient, buttonlen, button, textlen, text, objectcount, object, command. `key` is zero-based for indexed fields.','Always resolves the newest active server Gump, independently of an older SelectGump/InfoGump selection. `button[key]` is a real ButtonID; `command[key]` is the exact raw server layout command.','No active Gump/out-of-range key returns the field no-data sentinel; it does not silently read an older selected Gump.','VAR gid = UO.LastGump("gumpid")\nVAR btn = UO.LastGump("button", 0)\nVAR raw = UO.LastGump("command", 0)')
C['GetGump']=card('GetGump',['UO.GetGump(identifier:String) -> Any','UO.GetGump(identifier:String, key:Integer) -> Any','UO.GetGump(gumpId:Integer, identifier:String) -> Any','UO.GetGump(gumpId:Integer, identifier:String, key:Integer) -> Any'],'Any','Field-dependent Integer/String value from the selected/resolved active server Gump.','Same identifiers as LastGump. Explicit `gumpId` resolves stable InjID, then Serial/GumpID, then compatibility index.','Without explicit gump, reads the current SelectGump/InfoGump selection; if invalid, falls back to newest. `command[key]` is the exact raw server command and `button[key]` the real ButtonID.','Only active loaded server Gumps can be read.','UO.SelectGump(UO.LastGump("injid"))\nVAR raw = UO.GetGump("command", 0)')
C['SelectGump']=card('SelectGump',['UO.SelectGump(id:Variant) -> Unit'],'Unit','No value; updates the current GetGump/SetGump selection.','Primary selector is stable InjID; compatibility fallback accepts Yoko index, local Serial or server GumpID.','Selects one active server Gump. InjID stays stable for the lifetime of that active Gump.','Selection affects GetGump/SetGump only; LastGump remains newest and one-arg SendGumpSelect remains newest.','UO.SelectGump(UO.LastGump("injid"))')
C['GumpExists']=card('GumpExists',['UO.GumpExists(id:Variant) -> Integer','UO.GumpExists(serial:Variant, gumpId:Variant) -> Integer'],'Integer','1 if a matching active server Gump exists; otherwise 0.','One argument resolves InjID with compatibility fallback. Two arguments are Serial + GumpID; 0 in either field is wildcard.','Searches current non-disposed IsFromServer Gumps only.','GumpID 0 is valid; in the two-argument form 0 is wildcard by contract.','IF UO.GumpExists(0, 0x12345678) THEN\nEND IF')
C['SendGumpSelect']=card('SendGumpSelect',['UO.SendGumpSelect(buttonId:Integer) -> Unit','UO.SendGumpSelect(buttonId:String) -> Unit','UO.SendGumpSelect(buttonId:Integer, gumpIndex:Integer) -> Unit','UO.SendGumpSelect(buttonId:Integer, serial:Integer, gumpId:Integer) -> Unit','UO.SendGumpSelect(buttonId:Integer, serial:Integer, gumpId:Integer, injId:Integer) -> Unit'],'Unit','No value. Success means a real existing Button control executed its real ClassicUO action.','1 arg: newest active Gump. 2: Yoko index. 3: Serial/GumpID with 0 wildcard. 4: stable InjID selects the Gump.','Runtime first finds a real `Button` with matching ButtonID. Activate calls real `Gump.OnButtonClick`, which sends the actual 0xB1 GumpResponse with Serial/GumpID/ButtonID and disposes as normal. SwitchPage changes the actual page.','If Gump/Button is missing, no packet is sent, no Gump is falsely disposed, and runtime reports error.','UO.SendGumpSelect(77)\nUO.SendGumpSelect(77, 0)')
C['CancelGump']=card('CancelGump',['UO.CancelGump() -> Unit','UO.CancelGump(gumpIndex:Variant) -> Unit'],'Unit','No value. Zero-argument form cancels the active WaitGump generation.','No argument cancels WaitGump. One argument keeps the ClassicUO compatibility close-simple-gump extension.','WaitGump captures a generation token; CancelGump increments it and the wait loop exits instead of waiting for timeout.','Zero-argument CancelGump does not close a random Gump.','UO.CancelGump()')
C['GetGumpsCount']=card('GetGumpsCount',['UO.GetGumpsCount() -> Integer'],'Integer','Number of active non-ignored server Gumps in the Stealth-visible list.','No parameters.','Applies GumpID/Serial ignore sets before counting. Public Stealth GumpIndex order is oldest -> newest, therefore GetGumpsCount()-1 is the newest visible Gump.','This Stealth index ordering differs from Yoko InfoGumps index 0=newest.','VAR n = UO.GetGumpsCount()')
C['GetGumpInfo']=card('GetGumpInfo',['UO.GetGumpInfo(GumpIndex:Integer) -> Array'],'Array','Structured data for the valid filtered Stealth GumpIndex, or empty array for invalid index.','`GumpIndex` is resolved after ignore filtering, oldest -> newest.','Returns the resolved real Gump Serial, GumpID, text lines, button descriptions and full lines.','Ignored raw Gumps do not remain in the public index and cannot shift the command onto the wrong visible Gump.','VAR info = UO.GetGumpInfo(UO.GetGumpsCount() - 1)')
for name,subject in [('AddGumpIgnoreByID','GumpID'),('AddGumpIgnoreBySerial','Serial')]:
 C[name]=card(name,[f'UO.{name}({subject}:Integer) -> Unit'],'Unit','No value; adds one value to the runtime Gump ignore set.',f'`{subject}` is the server GumpID or local Gump Serial to ignore.','The filter is applied consistently to GetGumpsCount, indexed GetGump readers, GetGumpInfo, close actions and NumGump actions; visible Stealth indexes are recalculated after filtering.','Ignoring is client/runtime filtering and does not send a server cancel reply.',f'UO.{name}(0x12345678)')
C['ClearGumpsIgnore']=card('ClearGumpsIgnore',['UO.ClearGumpsIgnore() -> Unit'],'Unit','No value; clears both ignored GumpID and ignored Serial sets.','No parameters.','Still-open Gumps become visible to Stealth Gump APIs again and indexes are rebuilt immediately.','Does not reopen already-closed Gumps.','UO.ClearGumpsIgnore()')
for name,sig,what in [
 ('NumGumpButton','UO.NumGumpButton(GumpIndex:Integer, ButtonID:Integer) -> Boolean','executes a real existing Button action'),
 ('NumGumpCheckBox','UO.NumGumpCheckBox(GumpIndex:Integer, CheckBoxID:Integer, Value:Integer) -> Boolean','sets the real checkbox state'),
 ('NumGumpRadiobutton','UO.NumGumpRadiobutton(GumpIndex:Integer, RadioButtonID:Integer, Value:Integer) -> Boolean','sets the real radio-button state'),
 ('NumGumpTextEntry','UO.NumGumpTextEntry(GumpIndex:Integer, TextEntryID:Integer, Value:String) -> Boolean','sets the real text-entry value')]:
 C[name]=card(name,[sig],'Boolean','TRUE only when the filtered visible Gump and requested real control exist and the action/state change succeeds; otherwise FALSE.','`GumpIndex` is the filtered Stealth index (oldest -> newest); remaining parameters identify/control the real UI control.',f'Resolves ignore filtering first, then {what}. No fixed TRUE is fabricated.','Invalid index/control returns FALSE and does not redirect to another raw Gump.',f'VAR ok = UO.{name}(0, 0{", 1" if name!="NumGumpButton" and name!="NumGumpTextEntry" else ", \"x\"" if name=="NumGumpTextEntry" else ""})')

def replace_card(text,name,replacement):
    h=re.search(rf'^## `UO\.{re.escape(name)}`\s*$',text,re.M)
    if not h: raise RuntimeError(f'Manual card missing: {name}')
    next_cmd=re.search(r'^## `UO\.',text[h.end():],re.M); next_cat=re.search(r'^# [^#]',text[h.end():],re.M)
    candidates=[h.end()+m.start() for m in (next_cmd,next_cat) if m]
    bound=min(candidates) if candidates else len(text)
    segment=text[h.start():bound]; sep=segment.rfind('\n---'); end=h.start()+sep+4 if sep>=0 else bound
    return text[:h.start()]+replacement+text[end:]
for n,c in C.items(): s=replace_card(s,n,c)
note='''### v50.0.2 GumpIndex semantics\n\nFor Stealth-compatible indexed Gump APIs, `GumpIndex` is resolved after ID/Serial ignore filtering and ordered oldest -> newest. Ignored Gumps do not remain in count/read/action indexes; `GetGumpsCount()-1` is the newest visible Gump.\n\n'''
for n in ['GetGumpSerial','GetGumpID','IsGumpCanBeClosed','GetGumpTextLines','GetGumpShortLines','GetGumpFullLines','GetGumpButtonsDescription','CloseSimpleGump','CloseClientGump']:
    h=re.search(rf'^## `UO\.{re.escape(n)}`\s*$',s,re.M)
    if not h: continue
    nxt=re.search(r'^## `UO\.',s[h.end():],re.M); end=h.end()+nxt.start() if nxt else len(s); seg=s[h.start():end]
    if 'v50.0.2 GumpIndex semantics' in seg: continue
    ex=re.search(r'^### Examples\s*$',seg,re.M)
    if ex: s=s[:h.start()+ex.start()]+note+s[h.start()+ex.start():]
p.write_text(s,encoding='utf-8',newline='')
client=root.parent/'client/YokoDocumentation/Manual/COMPLETE_RUNTIME_API_MANUAL.md'; client.parent.mkdir(parents=True,exist_ok=True); client.write_text(s,encoding='utf-8',newline='')
print('v50.0.2 Manual updated and synchronized')
